package world.cepi.particle;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import world.cepi.particle.data.Color;
import world.cepi.particle.data.OffsetAndSpeed;
import world.cepi.particle.extra.*;
import world.cepi.particle.Particle.Type;
import net.minestom.server.particle.Particle;

@SuppressWarnings("ALL")
public class ParticleType {
    public static final @NotNull Type<@NotNull Color, @Nullable Nothing> AMBIENT_ENTITY_EFFECT = new ParticleTypes.Colored(Particle.AMBIENT_ENTITY_EFFECT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ANGRY_VILLAGER = new ParticleTypes.Default(Particle.ANGRY_VILLAGER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> BARRIER = new ParticleTypes.Default(Particle.BARRIER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> LIGHT = new ParticleTypes.Default(Particle.LIGHT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @NotNull BlockState> BLOCK = new ParticleTypes.Block(Particle.BLOCK);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> BUBBLE = new ParticleTypes.Default(Particle.BUBBLE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> CLOUD = new ParticleTypes.Default(Particle.CLOUD);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> CRIT = new ParticleTypes.Default(Particle.CRIT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DAMAGE_INDICATOR = new ParticleTypes.Default(Particle.DAMAGE_INDICATOR);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRAGON_BREATH = new ParticleTypes.Default(Particle.DRAGON_BREATH);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRIPPING_LAVA = new ParticleTypes.Default(Particle.DRIPPING_LAVA);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_LAVA = new ParticleTypes.Default(Particle.FALLING_LAVA);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> LANDING_LAVA = new ParticleTypes.Default(Particle.LANDING_LAVA);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRIPPING_WATER = new ParticleTypes.Default(Particle.DRIPPING_WATER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_WATER = new ParticleTypes.Default(Particle.FALLING_WATER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @NotNull Dust> DUST = ParticleTypes.DUST.INSTANCE;
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @NotNull DustTransition> DUST_COLOR_TRANSITION = ParticleTypes.DUST_COLOR_TRANSITION.INSTANCE;
    public static final @NotNull Type<@NotNull Color, @Nullable Nothing> EFFECT = new ParticleTypes.Colored(Particle.EFFECT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ELDER_GUARDIAN = new ParticleTypes.Default(Particle.ELDER_GUARDIAN);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ENCHANTED_HIT = new ParticleTypes.Default(Particle.ENCHANTED_HIT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ENCHANT = new ParticleTypes.Default(Particle.ENCHANT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> END_ROD = new ParticleTypes.Default(Particle.END_ROD);
    public static final @NotNull Type<@NotNull Color, @Nullable Nothing> ENTITY_EFFECT = new ParticleTypes.Colored(Particle.ENTITY_EFFECT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> EXPLOSION_EMITTER = new ParticleTypes.Default(Particle.EXPLOSION_EMITTER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> EXPLOSION = new ParticleTypes.Default(Particle.EXPLOSION);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @NotNull BlockState> FALLING_DUST = new ParticleTypes.Block(Particle.FALLING_DUST);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FIREWORK = new ParticleTypes.Default(Particle.FIREWORK);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FISHING = new ParticleTypes.Default(Particle.FISHING);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FLAME = new ParticleTypes.Default(Particle.FLAME);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SOUL_FIRE_FLAME = new ParticleTypes.Default(Particle.SOUL_FIRE_FLAME);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SOUL = new ParticleTypes.Default(Particle.SOUL);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FLASH = new ParticleTypes.Default(Particle.FLASH);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> HAPPY_VILLAGER = new ParticleTypes.Default(Particle.HAPPY_VILLAGER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> COMPOSTER = new ParticleTypes.Default(Particle.COMPOSTER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> HEART = new ParticleTypes.Default(Particle.HEART);
    public static final @NotNull Type<@NotNull Color, @Nullable Nothing> INSTANT_EFFECT = new ParticleTypes.Colored(Particle.INSTANT_EFFECT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @NotNull Item> ITEM = ParticleTypes.ITEM.INSTANCE;
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @NotNull Vibration> VIBRATION = ParticleTypes.VIBRATION.INSTANCE;
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ITEM_SLIME = new ParticleTypes.Default(Particle.ITEM_SLIME);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ITEM_SNOWBALL = new ParticleTypes.Default(Particle.ITEM_SNOWBALL);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> LARGE_SMOKE = new ParticleTypes.Default(Particle.LARGE_SMOKE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> LAVA = new ParticleTypes.Default(Particle.LAVA);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> MYCELIUM = new ParticleTypes.Default(Particle.MYCELIUM);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> NOTE = new ParticleTypes.Default(Particle.NOTE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> POOF = new ParticleTypes.Default(Particle.POOF);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> PORTAL = new ParticleTypes.Default(Particle.PORTAL);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> RAIN = new ParticleTypes.Default(Particle.RAIN);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SMOKE = new ParticleTypes.Default(Particle.SMOKE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SNEEZE = new ParticleTypes.Default(Particle.SNEEZE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SPIT = new ParticleTypes.Default(Particle.SPIT);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SQUID_INK = new ParticleTypes.Default(Particle.SQUID_INK);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SWEEP_ATTACK = new ParticleTypes.Default(Particle.SWEEP_ATTACK);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> TOTEM_OF_UNDYING = new ParticleTypes.Default(Particle.TOTEM_OF_UNDYING);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> UNDERWATER = new ParticleTypes.Default(Particle.UNDERWATER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SPLASH = new ParticleTypes.Default(Particle.SPLASH);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> WITCH = new ParticleTypes.Default(Particle.WITCH);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> BUBBLE_POP = new ParticleTypes.Default(Particle.BUBBLE_POP);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> CURRENT_DOWN = new ParticleTypes.Default(Particle.CURRENT_DOWN);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> BUBBLE_COLUMN_UP = new ParticleTypes.Default(Particle.BUBBLE_COLUMN_UP);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> NAUTILUS = new ParticleTypes.Default(Particle.NAUTILUS);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DOLPHIN = new ParticleTypes.Default(Particle.DOLPHIN);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> CAMPFIRE_COSY_SMOKE = new ParticleTypes.Default(Particle.CAMPFIRE_COSY_SMOKE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> CAMPFIRE_SIGNAL_SMOKE = new ParticleTypes.Default(Particle.CAMPFIRE_SIGNAL_SMOKE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRIPPING_HONEY = new ParticleTypes.Default(Particle.DRIPPING_HONEY);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_HONEY = new ParticleTypes.Default(Particle.FALLING_HONEY);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> LANDING_HONEY = new ParticleTypes.Default(Particle.LANDING_HONEY);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_NECTAR = new ParticleTypes.Default(Particle.FALLING_NECTAR);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_SPORE_BLOSSOM = new ParticleTypes.Default(Particle.FALLING_SPORE_BLOSSOM);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ASH = new ParticleTypes.Default(Particle.ASH);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> CRIMSON_SPORE = new ParticleTypes.Default(Particle.CRIMSON_SPORE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> WARPED_SPORE = new ParticleTypes.Default(Particle.WARPED_SPORE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SPORE_BLOSSOM_AIR = new ParticleTypes.Default(Particle.SPORE_BLOSSOM_AIR);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRIPPING_OBSIDIAN_TEAR = new ParticleTypes.Default(Particle.DRIPPING_OBSIDIAN_TEAR);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_OBSIDIAN_TEAR = new ParticleTypes.Default(Particle.FALLING_OBSIDIAN_TEAR);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> LANDING_OBSIDIAN_TEAR = new ParticleTypes.Default(Particle.LANDING_OBSIDIAN_TEAR);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> REVERSE_PORTAL = new ParticleTypes.Default(Particle.REVERSE_PORTAL);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> WHITE_ASH = new ParticleTypes.Default(Particle.WHITE_ASH);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SMALL_FLAME = new ParticleTypes.Default(Particle.SMALL_FLAME);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SNOWFLAKE = new ParticleTypes.Default(Particle.SNOWFLAKE);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRIPPING_DRIPSTONE_LAVA = new ParticleTypes.Default(Particle.DRIPPING_DRIPSTONE_LAVA);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_DRIPSTONE_LAVA = new ParticleTypes.Default(Particle.FALLING_DRIPSTONE_LAVA);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> DRIPPING_DRIPSTONE_WATER = new ParticleTypes.Default(Particle.DRIPPING_DRIPSTONE_WATER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> FALLING_DRIPSTONE_WATER = new ParticleTypes.Default(Particle.FALLING_DRIPSTONE_WATER);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> GLOW_SQUID_INK = new ParticleTypes.Default(Particle.GLOW_SQUID_INK);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> GLOW = new ParticleTypes.Default(Particle.GLOW);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> WAX_ON = new ParticleTypes.Default(Particle.WAX_ON);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> WAX_OFF = new ParticleTypes.Default(Particle.WAX_OFF);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> ELECTRIC_SPARK = new ParticleTypes.Default(Particle.ELECTRIC_SPARK);
    public static final @NotNull Type<@NotNull OffsetAndSpeed, @Nullable Nothing> SCRAPE = new ParticleTypes.Default(Particle.SCRAPE);
}